# Generated by Django 3.2.8 on 2021-10-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default='now', max_length=200),
            preserve_default=False,
        ),
    ]
