# Generated by Django 3.2.8 on 2021-10-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_birthdaydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.IntegerField(blank=True)),
                ('message', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Wish',
                'verbose_name_plural': 'Wishs',
            },
        ),
    ]
