# Generated by Django 3.2.8 on 2021-10-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_auto_20211016_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
